baseURL = 'https://sasakino.github.io/'
languageCode = 'ja-jp'
title = 'Subsumption'
author = "sasakino"
copyright = "© 2022 sasakino"
theme = 'holy'

[params]
    copyright = "© 2022 sasakino"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10